const router = require('koa-router')()
const public = require('./public')
const home = require('./home')
router.get('/', public.root)
      .get('/test', public.test)
      .get('/test1', public.test1)
      .get('/test2', public.test2)
      .get('/test3', public.test3)
      .get('/home', home.home)
      .post('/login', home.login)
      .post('/upload', home.upload)
module.exports = router
